#!name=爱企查

#!desc=爱企查vip

#!homepage=https://yfamilys.com

#!author=

#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/aqc.png



[Script]

爱企查vip=type=http-response,pattern=^https:\//aiqicha.baidu.com\/usercenter\/getvipinfoajax,requires-body=1,script-path=https://raw.githubusercontent.com/laiyangwuying/Shadowrocket-ADBlock-Rules-Forever/refs/heads/build/scripts/raw.githubusercontent.com/litieyin/AD_VIP/main/Script/aiqicha.0d6a389c41.js



[MITM]

hostname = %APPEND% aiqicha.baidu.com